spring:
  application:
    name: data-integration-twodb-api
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgresql:
      jdbc-url: jdbc:postgresql://localhost:5432/dataintegration
      username: admin
      password: password
      driver-class-name: org.postgresql.Driver

server:
  port: 8095

logging:
  level:
    root: INFO